// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Basket.API.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.29")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Basket.API.Models.ShoppingCart", b =>
                {
                    b.Property<string>("Username")
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("Username");

                    b.HasKey("Username");

                    b.ToTable("ShoppingCarts", (string)null);
                });

            modelBuilder.Entity("Basket.API.Models.ShoppingCart", b =>
                {
                    b.OwnsMany("Basket.API.Models.ShoppingCartItem", "Items", b1 =>
                        {
                            b1.Property<string>("ShoppingCartUsername")
                                .HasColumnType("nvarchar(200)");

                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<string>("Color")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<decimal>("Price")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<Guid>("ProductId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("ProductName")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<int>("Quantity")
                                .HasColumnType("int");

                            b1.HasKey("ShoppingCartUsername", "Id");

                            b1.ToTable("ShoppingCartItem");

                            b1.WithOwner()
                                .HasForeignKey("ShoppingCartUsername");
                        });

                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
